# Generated by Django 2.1.5 on 2020-06-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0003_auto_20200622_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
